name: Monthly build

on:
    schedule:
        - cron: '0 1 1 * *'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: master
          - name: Monthly build
            uses: HurricanKai/Publish-Docker-Github-Action@master
            with:
              name: monolithprojects/systemd-fedora36
              username: monolithprojects
              password: ${{ secrets.TOKEN }}
              registry: docker.io
              dockerfile: Dockerfile
              snapshot: true